INSERT INTO COMPUTER (COM_ID, COM_NAME)
VALUES (NULL, 'testPC');

INSERT INTO NETWORK_INTERFACE_CARD (NIC_ID, NIC_COM_ID, NIC_MAC_ADDRESS, NIC_IP_ADDRESS, NIC_SUBNET_MASK, NIC_DNS, NIC_GATEWAY, NIC_DOMAIN)
VALUES (NULL, 1, '02:T5:22:TZ:EA:A1', '192.168.0.110', '255.255.255.0', '192.168.0.1', '192.168.0.1', 'local.test');

INSERT INTO OPERATING_SYSTEM (OSY_ID, OSY_NAME)
VALUES (NULL, 'Windows XP');

INSERT INTO SOFTWARE (SOF_ID, SOF_NAME, SOF_VERSION_NUMBER) 
VALUES (NULL, 'Excel', '2010 Prof.');

INSERT INTO MAPPING_COMPUTER_OPERATING_SYSTEM (MCO_ID, MCO_COM_ID, MCO_OSY_ID)
VALUES (NULL, 1, 1);

INSERT INTO MAPPING_COMPUTER_SOFTWARE (MCS_ID, MCS_COM_ID, MCS_SOF_ID)
VALUES (NULL, 1, 1);

